---
- name: Install EPEL repository
  yum:
    name: epel-release
    state: present

- name: Install Nginx on Linux server
  become: true
  yum:
    name: nginx
    state: present  

- name: Starting nginx service
  service:
    name: nginx
    state: started
    enabled: yes

