---
- name: Install EPEL repository
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: Install Nginx on Linux server
  become: true
  yum:
    name: nginx
    state: present  

- name: Starting nginx service
  service:
    name: nginx
    state: started
    enabled: yes

