---
- name: Install Nginx on Linux server
  become: true
  tasks:
    - name: Installing nginx
      yum:
        name: nginx
        state: present

    - name: Starting nginx service
      service:
        name: nginx
        state: started
        enabled: yes

